export * from '../components/Albums/Albums'
export * from './NotFoundPage/NotFoundPage';
export * from './PostCommentsPage/PostCommentsPage';
export * from './PostDetailPage/PostDetailPage';
export * from './PostsPage/PostsPage';
export * from './UserAlbumsPage/UserAlbumsPage';
export * from './UserDetailPage/UserDetailPage';
export * from './UserPostsPage/UserPostsPage';
export * from './UsersPage/UsersPage';
export * from './PhotosPage/PhotosPage';
