export * from './Albums/Albums'
export * from './Comment/Comment';
export * from './DetailPost/DetailPost';
export * from './Header/Header';
export * from './Layout/Layout';
export * from './Post/Post';
export * from './UserDetail/UserDetail';
export * from './UserPosts/UserPosts'
export * from './Users/Users';
export * from './Photo/Photo'
